name: CashCompass CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

defaults:
  run:
    working-directory: ./backend
jobs:
  integrate_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Clean install
        run: npm ci
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: npm test
      - name: Run build
        run: npm run build
