name: CashCompass CD

on:
  push:
    branches: [main]

jobs:
  deploy_to_render:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
