name: CashCompass CI

on:
  pull_request:
    branches: [main]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: cd backend && npm ci
      - run: cd backend && npm test
      - run: cd backend && npm run build
